version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - .env

  frontend:
    image: zloybaklan/infra_frontend_1:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  backend:
    image: zloybaklan/infra_backend_1:latest
    restart: always
    volumes:
      - static_value:/code/dj_static/
      - media_value:/code/dj_media/
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - static_value:/code/dj_static/
      - media_value:/code/dj_media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    restart: always
    depends_on:
      - backend
      - frontend
volumes:
    postgres_data:
    static_value:
    media_value: